[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

# (opcional) headers de caché agresiva para tus fotos
[[headers]]
  for = "/photos/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
